image: node:16.5.0

# cache:
#   paths:
#     - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm run build -r './'
    - cp -a docs/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
